name: Build Standalone Application

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile and Build 4D Standalone
        uses: 4d/build4d-action@v1
        with:
          project: 'Project/EA_Invoices.4DProject'
          targets: 'standalone'
          product-line: '20.x'
          version: '20.3'

      - name: Upload Built Application as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: EA_Invoices-Windows
          path: |
            Build/
            BuiltApplication/
          if-no-files-found: error
